### ISSUE TITLE
Hope to provide the installation package, thank you

### ISSUE THREAD

**Issue by k2913064** [Magisk-Modules-Repo/ARCore_enabler#14]
Hope to provide the installation package, thank you

**Comment by MarcAnt01** [comment]
Hello, unfortunately I do not have any backup of the files. Since @topjohnwu shut down the Magisk Modules repo without notifying us.
Anyway, since the code is still here apparently, what you can do it to download the code of this GitHub repository as a zip, create a new zip with any program like WinZip, WinRar or your file manager (for example the one in Windows 11 works just fine) and flash this new zip. If you have any other doubts, feel free to ask

**Comment by k2913064** [comment]
Thank you very much for the author's reply, but I tried to download the code zip of github before, but it showed an error through magisk installation, I don't know why...

**Comment by MarcAnt01** [comment]
> Thank you very much for the author's reply, but I tried to download the code zip of github before, but it showed an error through magisk installation, I don't know why...

This is totally intended, the compression of .zip source code GitHub is different from the one of a normal zip and Magisk manager cannot install modules from there.
As I told you in the previous message you need to unzip and then create a new zip, in this way it'll work

**Comment by k2913064** [comment]
Hello author, I tried to decompress it first and then recompress it into a zip file, but the installation through magisk still failed... I don’t know the reason, I want to give up😆

**Comment by MarcAnt01** [comment]
Maybe things have changed with the years, haven't been using Magisk for years. Anyway, here's a direct link https://www.celsoazevedo.com/files/random/ARCore_Playground_Patcher-v2.1.zip 
Let me know if it works for you

**Comment by Sostay** [comment]
> Thanks to the author, this installation package can be used感谢作者，这个安装包可以用

Does it still work fine now?

**Comment by Sostay** [comment]
> Maybe things have changed with the years, haven't been using Magisk for years. Anyway, here's a direct link https://www.celsoazevedo.com/files/random/ARCore_Playground_Patcher-v2.1.zip Let me know if it works for you

yes,it does works!

**Comment by gangoogle** [comment]
i will try it

**Comment by MoLu12138** [comment]
unzip error ,why?

**Comment by MarcAnt01** [comment]
> unzip error ,why?

Where are you downloading the file from?

**Comment by MarcAnt01** [comment]
Well, I guess since I have no received no reply in months, I'm closing this
