### ISSUE TITLE
ARCore Enabler causes Google Camera issues

### ISSUE THREAD

**Issue by julian-fairfax** [Magisk-Modules-Repo/ARCore_enabler#4]
Hello,
I have a Mi A2 Lite where I have installed Google Camera and now flashed ARCore enabler. Unfortunately, after flashing the former, Google Camera doesn’t work with HDR+, Night Shift, or Portrait. I’ve tried changing the base settings for the front and back camera but that causes no difference. Is there anything I can about this or do I have to live with one or the other?

**Comment by MarcAnt01** [comment]
What GCam are you using?

**Comment by julian-fairfax** [comment]
A modified version of 6.3.0.17.253834016 for my device that I found in a Telegram group. Works well. https://t.me/A2LiteOfficial/99330

**Comment by MarcAnt01** [comment]
Well, I just enable ARCore by changing the fingerprint, if the GCam doesn't work like before just by changing the fingerprint, I think that it is a bug of this GCam version

**Comment by julian-fairfax** [comment]
That’s possible but since the original source of my port is a Russian group, I’ll never find out. No AR for me I guess :/
