### ISSUE TITLE
Not working on Redmi 7 (32 bit )

### ISSUE THREAD

**Issue by NightmareLele135** [Magisk-Modules-Repo/ARCore_enabler#5]
I tried to use AR Core on some apps but it didn't function in any of these. My device is a redmi 7 and the apps I tested are ARuler, Pokémon GO and 7DS Grand Cross.

**Comment by MarcAnt01** [comment]
Have you installed Google Play Services for AR?

**Comment by NightmareLele135** [comment]
> Have you installed Google Play Services for AR?

Yes, of course, when I try an app I see the loading screen but it never loads

**Comment by MarcAnt01** [comment]
> > Have you installed Google Play Services for AR?
> 
> Yes, of course, when I try an app I see the loading screen but it never loads
> Edit: it doesn't concern anything with this issue but if you want me to be more clear I can write in Italian because it's my native language

Sicuro di aver installato la versione per Arm32 visto il Redmi 7 non è Arm64?

**Comment by NightmareLele135** [comment]
> > > Have you installed Google Play Services for AR?
> > 
> > 
> > Yes, of course, when I try an app I see the loading screen but it never loads
> > Edit: it doesn't concern anything with this issue but if you want me to be more clear I can write in Italian because it's my native language
> 
> Sicuro di aver installato la versione per Arm32 visto il Redmi 7 non è Arm64?

Non ne sono sicuro provo a reinstallarlo scegliendo la giusta versione

**Comment by MarcAnt01** [comment]
> > > > Have you installed Google Play Services for AR?
> > > 
> > > 
> > > Yes, of course, when I try an app I see the loading screen but it never loads
> > > Edit: it doesn't concern anything with this issue but if you want me to be more clear I can write in Italian because it's my native language
> > 
> > 
> > Sicuro di aver installato la versione per Arm32 visto il Redmi 7 non è Arm64?
> 
> Non ne sono sicuro provo a reinstallarlo scegliendo la giusta versione

OK, avevo il tuo stesso problema quella volta che ho installato la versione sbagliata

**Comment by NightmareLele135** [comment]
> > > > > Have you installed Google Play Services for AR?
> > > > 
> > > > 
> > > > Yes, of course, when I try an app I see the loading screen but it never loads
> > > > Edit: it doesn't concern anything with this issue but if you want me to be more clear I can write in Italian because it's my native language
> > > 
> > > 
> > > Sicuro di aver installato la versione per Arm32 visto il Redmi 7 non è Arm64?
> > 
> > 
> > Non ne sono sicuro provo a reinstallarlo scegliendo la giusta versione
> 
> OK, avevo il tuo stesso problema quella volta che ho installato la versione sbagliata

Il problema persiste ed ho provato con tutti tipi di versione, stavo pensando che magari non funziona con la versione più recente.

**Comment by MarcAnt01** [comment]
Credo dipenda da un bug dell’app e non da modulo, per esserne sicuro mi servirebbe il logcat

**Comment by MarcAnt01** [comment]
I cannot do anything without logs
