### ISSUE TITLE
This module don't work.

### ISSUE THREAD

**Issue by aiivy782** [Magisk-Modules-Repo/ARCore_enabler#6]
I go to GCam, click Playground and it does not open, although the very latest ARCore is installed. My phone ASUS ZenFone Max Pro M1.

**Comment by MarcAnt01** [comment]
Have you installed patched Playground?

**Comment by aiivy782** [comment]
Hi! No, I have Playground from Google Play.

вс, 26 апр. 2020 г., 12:43 Filippo Fedeli <notifications@github.com>:

**Comment by MarcAnt01** [comment]
Then, it's normal. Take a look at the Readme

**Comment by aiivy782** [comment]
OK, thanks!

вс, 26 апр. 2020 г., 12:49 Filippo Fedeli <notifications@github.com>:
