### ISSUE TITLE
Not working on Redmi S2

### ISSUE THREAD

**Issue by creepercrack** [Magisk-Modules-Repo/ARCore_enabler#7]
Hello,

I've tried to use "ARCore" on some apps but it didn't function
My device is a Redmi S2 and the apps I tested are "Minecraft Earth" and "Google Arts & Culture"

I have "Google Play Services for AR" installed from the "Google Play Store" itself
The apps are also installed from the "Google Play Store"

In order to be able to install these apps I had to install your module into the "Magisk" after installation I rebooted the device
The device uses MIUI Global 11.0.5.0 Stable with android 9 PKQ1.181203.001 (the stock image)
I have tried using different versions of "ARCore", but they don't work

The apps I've tried work but when they try to use "ARCore" either they crash or show a black screen (always the same behavior on the same apps)
I can serve logs if you want them

Thank you!

**Comment by MarcAnt01** [comment]
Hello, ARCore seems to have some specific problems with Arm32 software on Arm64 hardware. It's already ben reported here https://github.com/Magisk-Modules-Repo/ARCore_enabler/issues/5 , but they guy didn't provide any logs, I'd appreciate if you could send the logs, but am not sure this is something I can fix

**Comment by creepercrack** [comment]
Hello,

So what I did is reboot the device and opened Minecraft Earth first, then I went into the AR session and I took a screenshot
Then I closed the app and opened the Google Arts & Culture, then I went into the AR session and took a screenshot
Then I copied the Catlog

Thank you for your fast response and for pointing the 32-bit SW on 64-bit HW

Logcat: [logcat_07-26-2020_15-19-01.txt](https://github.com/Magisk-Modules-Repo/ARCore_enabler/files/4977718/logcat_07-26-2020_15-19-01.txt)

Minecraft Earth screenshot:
<img src="https://user-images.githubusercontent.com/47305546/88480470-50ebf700-cf56-11ea-868b-ed36fcf4e477.jpg" width="250">

Google Arts & Culture screenshot:
<img src="https://user-images.githubusercontent.com/47305546/88480472-521d2400-cf56-11ea-9911-d4ee4e1fba35.jpg" width="250">

**Comment by philtc** [comment]
I had a quick look at your logcat and noticed the following line:
`INTERNAL:` Physical cameras don't match device profile. Camera not found. camera_id=0, cameras count=0 at `third_party/arcore/ar/infrastructure/android/cameras.cc:142`
I had a similar problem on the XiaoMi 4c and needed to get camera2api working to fix it (am still having other issues though).

**Comment by MarcAnt01** [comment]
Hi @philtc thanks for your comment, @creepercrack can you try to enable camera2api and tell me if it fixed your issue?

**Comment by MarcAnt01** [comment]
I am closing that, since I have got no reply
