### ISSUE TITLE
Broken on Q

### ISSUE THREAD

**Issue by skff-err** [Magisk-Modules-Repo/ARCore_enabler#8]
ARCore playground patcher breaks the lockscreen

inputting the correct password on the lockscreen won't let the user go to the homescreen. Instead, it crashes the lockscreen and the user would still have to input the password which will, again, crash the lockscreen.

trying to change the lockscreen password by going to security>lockscreen> inputting the correct password would result in it telling that the password is incorrect.

Fingerprint lock would also fail. 

Deleting locksettings.* in /data/system would allow the user to access homescreen but still wouldn't be able to register a new lockscreen until the module is deleted/disabled

DEVICE TESTED:
Samsung Galaxy S5 SM-G900F (klte) Snapdragon 801 (armv7)
ROM where the bug was encountered: [https://forum.xda-developers.com/galaxy-s5/unified-development/crdroidv6-t4039471](url) (Version 6.7)

**Comment by MarcAnt01** [comment]
The module is quite simple performing minimal changes, so it can't be the cause of breaking lockscreen, this looks mostly like a Rom issue with Magisk or just a Magisk issue
