### ISSUE TITLE
Redmi note 5 pro arcore with depth api support

### ISSUE THREAD

**Issue by Rogue98** [Magisk-Modules-Repo/ARCore_enabler#9]
Redmi note 5 pro is not officially supported by arcore. I installed this module and then installed arcore by google from play store. When you search Tiger in google it used to work to show a tiger with depth api which can do ar occlusion few months ago. Now it doesn't work and arcore is broken and shows only black screen. 
I wanted to test the arcore depth lab but that also shows black screen only no camera. I was able to use arcore elements and also play minecraft earth cause of this. Also playground ar works on google camera.

**Comment by MarcAnt01** [comment]
I am closing this issue and making the other issue of yours more general
